# %% CARGA CSV DATOS ORIGINALES
# ENRIQUECEMOS AUTOMÁTICAMENTE
# %% CALUCULO VUELO
# MODELO ML
# %% CARGO DATOS TERRENO
# UNION A TERRENO
# %% CARGO DATOS METEOROLÓGICOS
# UNION VUELO METEOROLOGÍA
# FUNCIÓN BÚSQUEDA POSICION PAJARO, PUEBLO MÁS CERCANO
